site_name: Portal Cascata - Docs

pages:
  - Home: index.md
  - Justificativa Metodológica: justificativa.md
  - Engenharia de Requisitos:
    - Introdução: requisitos/requisitos.md
    - Rich Picture: requisitos/richpicture.md
    - 5W2H: requisitos/5w2h.md
    - Ishikawa: requisitos/ishikawa.md
    - NFR Framework: requisitos/nfr.md
    - I*: requisitos/istar.md
    - Perfil de Usuário: requisitos/perfil-usuario.md
    - Elicitação:
      - Introdução: requisitos/elicitacao/elicitacao.md
      - Entrevistas: requisitos/elicitacao/entrevistas.md
      - Análise de Protocolo: requisitos/elicitacao/protocolos.md
      - Protótipo: requisitos/elicitacao/prototipo.md
    - Modelagem:
      - Léxicos: requisitos/modelagem/lexicos.md
  - Gerenciamento do Projeto:
     - Cronograma: cronograma.md
  - Folha de Estilo: folha_estilo.md
  - Backlogs:
     - Épicos: requisitos/epicos.md
     - Features: requisitos/features.md
     - Histórias de Usuários: requisitos/backlogproduct.md
theme: material

markdown_extensions:
  - codehilite
